### ISSUE TITLE
How to use old code with display()？

### ISSUE THREAD

**Issue by wuyudi** [vpython/vpython-jupyter#100]
Here is a [webpage](https://wizardforcel.gitbooks.io/hyry-studio-scipy/content/10.html#)

Here is code:

```python
from vpython import *
display(title=u"坐标轴".encode("gb2312"), width=300, height=300)
arrow(pos=(1,0,0), axis=(1,0,0), color=(1,0,0))
arrow(pos=(0,1,0), axis=(0,1,0), color=(0,1,0))
arrow(pos=(0,0,1), axis=(0,0,1), color=(0,0,1))
```

I tried to run it , but I don't see anything.

It returns that

> NameError: name 'display' is not defined

So how to solve it?

I tried to delete `display(title=u"坐标轴".encode("gb2312"), width=300, height=300)` ,and get nothing.

![image](https://user-images.githubusercontent.com/30024051/84173805-4c828200-aa6d-11ea-80a1-bbd173fe3866.png)

**Comment by BruceSherwood** [comment]
Please go to this section of the documentation: 

https://www.glowscript.org/docs/VPythonDocs/experienced.html

"display" is now "canvas", and vectors MUST be in the form vec(x,y,z) or vector(x,y,z).
