### ISSUE TITLE
Compound origin bug

### ISSUE THREAD

**Issue by BruceSherwood** [vpython/vpython-jupyter#15]
Omitting an origin attribute from the constructor for a compound object leads to "AttributeError: 'compound' object has no attribute '_origin'"

**Comment by WolfgangFahl** [comment]
see https://stackoverflow.com/questions/57175489/attributeerror-compound-object-has-no-attribute-origin-in-vpython-py

**Comment by BruceSherwood** [comment]
Bug has been addressed: https://github.com/vpython/vpython-jupyter/commit/bf0aeeaa986835c27bc673979379ab1304ba7b05
