### ISSUE TITLE
scene.capture() does not include labels

### ISSUE THREAD

**Issue by eltos** [vpython/vpython-jupyter#152]
The function `scene.capture(filename)` does not consider labels.  

Execute the following code in a jupyter notebook:
```python
from vpython import *
sphere()
label(text='TEXT')
scene.capture('image.png')
```
|Expected output|Actually saved|
|-|-|
|![image.png](https://user-images.githubusercontent.com/19860638/117710397-5dce9400-b1d2-11eb-91d9-dbcc3a298995.png)|![image.png](https://user-images.githubusercontent.com/19860638/117710422-658e3880-b1d2-11eb-823f-013f66a04c65.png)

I noticed that there are two `canvas` elements in the HTML, one containing the labels, and the other being a placeholder for the 3D objects:
```html
<div class="glowscript-canvas-wrapper ui-resizable" style="display: inline-block; position: relative; float: none;">
    <canvas style="position: absolute;" width="640" height="400"></canvas>
    <canvas style="position: relative; background-color: transparent;" width="640" height="400"></canvas>
    <div class="ui-resizable-handle ui-resizable-e" style="z-index: 90;"></div>
    <div class="ui-resizable-handle ui-resizable-s" style="z-index: 90;"></div>
    <div class="ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se" style="z-index: 90;"></div>
</div>
```

It seems that the capturing function [here](https://github.com/vpython/glowscript/blob/c65dabfa081f71750bbc4f80da7fc0cfa331980b/lib/glow/canvas.js#L315) only considers one of them.

**Comment by BruceSherwood** [comment]
The issue is that labels are displayed in a transparent 2D canvas in front of the 3D WebGL canvas, and the GlowScript code is only able to capture the 3D canvas. A workaround is to use the 3D text object instead of a label (and note that you can billboard the text object, like a label).

**Comment by BruceSherwood** [comment]
Thanks for the suggestion. Have you tested your proposed suggestion?

**Comment by eltos** [comment]
> Thanks for the suggestion. Have you tested your proposed suggestion?

@BruceSherwood Yes, I tested this approach successfully. Please find my MR here: https://github.com/vpython/glowscript/pull/148

**Comment by BruceSherwood** [comment]
I tried your code in GlowScript VPython 3.2dev, and it never returns from this line:

await new Promise(r => img.onload=r); // wait for image to be loaded

??

**Comment by BruceSherwood** [comment]
I tried your code with GlowScript VPython 3.2dev, and it hangs for me on this statement:

await new Promise(r => img.onload=r); // wait for image to be loaded

??

**Comment by eltos** [comment]
@BruceSherwood I tested this code using jupyter notebook with Firefox without any issues.
I had noticed that the image returned by the renderer's screenshot method was not loaded in time for it to be drawn onto the canvas, hence I added this line of code.
Maybe in your environment, it is loaded even before the Promise statement is reached?
Can you try surrounding the line in question with an `if (!img.complete){}`?

**Comment by eltos** [comment]
Alternatively (maybe better) you can replace the line with `await img.decode();`, which is essentially the same (it returns a promise) but should handle either case.
