### ISSUE TITLE
Embedding VPython Jupyter Notebook Output in Another Application

### ISSUE THREAD

**Issue by bacalfa** [vpython/vpython-jupyter#18]
Is it possible? Or in an HTML frame?

In other words, I'd like to execute a cell in Jupyter Notebook and "export" its output, which may be an animation (i.e., not just a single image).

I saw this suggestion: https://stackoverflow.com/a/41981015/2359430. But I can't get a simple example to work (it times out).

**Comment by BruceSherwood** [comment]
From the VPython documentation on canvases:

capture(filename) Sends to your Download folder a png screen shot of the canvas. If filename is the string "boxes" or "boxes.png" the file will be named "boxes.png".

So with scene.capture(filename) you can export a png image, and in a loop you could export a series of png images. I assume that there exist mechanisms for stitching together a series of png images into a movie.

Another option is that if vpython is the only module you import, you could run your program at glowscript.org and, in the editor, click "Share or export this program" which generates code that can be inserted into a web page. Here is an example of an exported animation running in a web page:

https://brucesherwood.net/?p=191

Note that this is more than a mere movie: the viewer can start and stop the animation or use the standard VPython zoom and rotate and pan controls to change the view.

**Comment by Heusini** [comment]
Is it possible to add a function that can save to a jupyter folder instead of downloading the image?

**Comment by BruceSherwood** [comment]
That would be very low priority, since you can always move the downloaded images to another folder.

**Comment by BruceSherwood** [comment]
I should also comment that the downloading of a screen capture is necessarily done from within the browser (where the WebGL library is located), and the browser is restricted for security reasons to downloading to the download folder. For the architecture of VPython, see https://vpython.org/contents/VPythonArchitecture.pdf
