### ISSUE TITLE
Problems with Carnets PLus on iPad

### ISSUE THREAD

**Issue by Peter230655** [vpython/vpython-jupyter#181]
I use python on my iPad, using the (very good!!) app Carmets PLus, which is a Jupiter Notebook.
I started to play around with vpython.
When I open a new notebook, it seems to work fine, but when I close the notebook, reopen it and try to run it again, it seems to enter some 'infinite loop': it seems to calculate something, but the result never comes.

Any help would be GREATLY appreciated!!

**Comment by BruceSherwood** [comment]
I asked him to post to the VPython forum, which he did.
