### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jmspereira** [vpython/vpython-jupyter#230]
Hey, do you have any news on when a new release is going to be published?

I'm particularly interested in the changes introduced in this commit:
https://github.com/vpython/vpython-jupyter/commit/c82ef49ed4efc0d73d72be22c9ac9c65b579db17

Thank you!

**Comment by BruceSherwood** [comment]
Because the developers are academics, I don't expect another release before summer. Of course you could edit your own copy of the vpython module.
