### ISSUE TITLE
Jupyterlab extension for Jupyterlab >= 4.0.0

### ISSUE THREAD

**Issue by paulkim3151** [vpython/vpython-jupyter#241]
Currently, the vpython extension is available only for JuptyerLab 3.
Can we have a vpython extension for JuptyerLab 4?

I would appreciate it if you could let me know if you have any plans to proceed with such updates.

**Comment by jcoady** [comment]
There is now a new jupyterlab extension for vpython on pypi.org that works with jupyterlab version 4.x and vpython version 7.6.4. You can install the updated jupyterlab-vpython extension on jupyterlab 4.x with the command.

   pip install jupyterlab-vpython
