### ISSUE TITLE
Triangle not rendered.

### ISSUE THREAD

**Issue by nastasi** [vpython/vpython-jupyter#76]
Using this snippet from linux console and vpython 7.6.0 from pypi :
```
#!/usr/bin/env python3
from vpython import vector as vec
from vpython import *

a = vertex( pos=vec(0,0,0) )
b = vertex( pos=vec(1,0,0) )
c = vertex( pos=vec(1,1,0) )
T = triangle( v0=a, v1=b, v2=c)
```
 and interfacing with chrome Version 79.0.3945.130 (Official Build) unknown (64-bit) I obtain this error in the development console:
```
Uncaught Error: A triangle does not have a canvas; its vertex objects do.
    at new triangle (glow.min.js:1)
    at triangle (glow.min.js:1)
    at handle_cmds ((index):645)
    at handler ((index):530)
    at WebSocket.ws.onmessage ((index):74)
```
Is it a sort of misalignment between components or I' m doing something wrong in the snippet ?

**Comment by BruceSherwood** [comment]
This bug was reported in the VPython forum and is fixed in the new version about to be released.
