### ISSUE TITLE
extrusion seems doesn't support smooth.

### ISSUE THREAD

**Issue by nastasi** [vpython/vpython-jupyter#81]
Creating these skittles using ``extrusion`` I cannot obtain smoothing setting ''smooth'' attrib to any value between 0 and 1.
Using ``paths.circle(radius=0.0001, np=16)``, with ``paths.circle(radius=0.0001, np=32)`` works fine also without ``smooth`` param.
![skittle_wrong](https://user-images.githubusercontent.com/1143141/75326812-98713880-587b-11ea-8630-30c378237fba.png)

**Comment by BruceSherwood** [comment]
The problem is an oversight in VPython 7, which doesn't send the value of "smooth" from Python to the browser. Thanks much for the report.

**Comment by nastasi** [comment]
@BruceSherwood if it is an open issue maybe you can keep it **open** as reminder and **close** it when it is, just a suggestion of a good practice.

**Comment by mwcraig** [comment]
Was this fixed in one of the pull requests yesterday?

**Comment by nastasi** [comment]
@mwcraig I placed it in the wrong issue, I'm sorry.
