### ISSUE TITLE
camera.rotation strange behavior.

### ISSUE THREAD

**Issue by nastasi** [vpython/vpython-jupyter#82]
Using the code:
```python
scene.camera.rotate(angle=-5.0 * PI / 180.0,
                                axis=scene.up,
                                origin=scene.center)
```
where:
  * scene.up is <0, 1, 0>
  * scene.center is <0, 0, 0>

From this top view:
![before](https://user-images.githubusercontent.com/1143141/75353060-06812400-58ab-11ea-87cb-949f00f67131.png)

I obtain this:
![after](https://user-images.githubusercontent.com/1143141/75353106-17319a00-58ab-11ea-948d-303e0ef1222b.png)

That doesn't seems what I was expecting, there is some error or I misunderstood the doc ?

**Comment by BruceSherwood** [comment]
Thanks for the report. There is indeed a typo in the machinery for scene.camera.rotate(). Here is a workaround. Not quite sure why the range statement is needed.

scene.range = 4
box(size=vec(2,5,3))
scene.camera.axis = scene.camera.axis.rotate(angle=-pi/4, axis=scene.up)
scene.center = vec(0,0,0)

**Comment by nastasi** [comment]
@BruceSherwood I'm still in trouble: I was interested to rotate the camera at the right (or the left) of the current position still looking the center of the scene (like an helicopter when it flies around an target).
Tnx.

**Comment by nastasi** [comment]
@BruceSherwood I think to have found the source of my problems: moving the view using the mouse on the web page the ``scene.camera.up`` vector is still (0,1,0)

**Comment by BruceSherwood** [comment]
I don't understand. I thought that the workaround code I provided did exactly that: move the camera around the center of the scene.
