### ISSUE TITLE
Shape roundness bug

### ISSUE THREAD

**Issue by ianzur** [vpython/vpython-jupyter#90]
Using shape roundness argument results in extrusion missing front and end faces.

```
from vpython import *

print(version)
print(GSversion)

### works as expected
# rt = shapes.rectangle(width=3, height=3)

### start and end faces missing
rt = shapes.rectangle(width=3, height=3, roundness=0.1)

extrusion(
    path=[vec(0,0,0), vec(0,0,-0.1)],
    shape=rt
    )

```
![bug](https://user-images.githubusercontent.com/33916505/79053325-1dcd6400-7c02-11ea-9a61-09998d45152e.jpg)

['7.6.1', 'jupyter']
['2.9', 'glowscript']

**Comment by BruceSherwood** [comment]
Thanks much for this detailed report. Will look into it.

**Comment by BruceSherwood** [comment]
Replace .../Lib/site-packagesvpython/shapespath.py with this file: 
 https://github.com/vpython/vpython-jupyter/blob/master/vpython/shapespaths.py
The next release of VPython 7 will contain this fix, which turned out to be an off-by-one error in generating points along the shape.

**Comment by ianzur** [comment]
Thank you for the quick fix Bruce!
