### ISSUE TITLE
How to use it in Google colab?

### ISSUE THREAD

**Issue by okadath** [vpython/vpython-jupyter#91]
![Screenshot from 2020-04-11 21-10-22](https://user-images.githubusercontent.com/29925635/79058887-0493da00-7c39-11ea-8236-86ec20c2d2ac.png)
hangs without render anything.
I do the following steps to install the environment:
```
!apt install curl
!curl -sL https://deb.nodesource.com/setup_10.x | bash -
!apt-get install -y nodejs
!node -v
!pip install vpython
!jupyter labextension install vpython
```

**Comment by BruceSherwood** [comment]
What (if anything) do you see if instead of making a box you say print(version)? Are you working within an Anaconda environment, which is recommended? If you are in Anaconda, it is recommended to execute "conda install -c vpython vpython" rather than pip.

**Comment by okadath** [comment]
still not render :( 
```
!wget -c https://repo.anaconda.com/miniconda/Miniconda3-4.5.4-Linux-x86_64.sh
!chmod +x Miniconda3-4.5.4-Linux-x86_64.sh
!bash ./Miniconda3-4.5.4-Linux-x86_64.sh -b -f -p /usr/local
!yes | conda install -c vpython vpython
import sys
sys.path.append('/usr/local/lib/python3.6/site-packages')
!python -V
```
```
$Python 3.6.5 :: Anaconda, Inc.
```
```
import vpython 
vpython.__version__
```
```
$'7.6.1'
```

**Comment by BruceSherwood** [comment]
Okay, the next thing to test is to go to https://get.webgl.org.  You should see a rotating box and a title "Your browser supports WebGL". (WebGL is the 3D graphics library built into modern browsers, which VPython uses to do the 3D rendering.) A closely related issue is that your graphics card must be capable of executing GPU code. What browser do you use?

**Comment by okadath** [comment]
![Screenshot from 2020-04-14 14-07-30](https://user-images.githubusercontent.com/29925635/79263949-57e47300-7e59-11ea-8293-55ba03318ce6.png)
in my pc runs perfectly, the problem is only in google colab

**Comment by okadath** [comment]
![Screenshot from 2020-04-14 14-11-37](https://user-images.githubusercontent.com/29925635/79264253-e527c780-7e59-11ea-9090-ff3183d6d78c.png)
this is in my laptop, Mozilla Firefox

**Comment by BruceSherwood** [comment]
Sorry, I didn't read carefully enough to know that the problem occurs ONLY in Jupyter lab. I'll ask a colleague about this.

**Comment by okadath** [comment]
Thank you very much for answering

**Comment by BruceSherwood** [comment]
I apologize that although you kept saying "colab" I kept thinking "lab". While VPython does run in Jupyter lab, it does not (yet) run in colab, Our expert on Jupyter lab has looked into colab but has not found a way to make VPython work there.
