### ISSUE TITLE
jupyterlab extension for Jupyterlab >= 2.0.0

### ISSUE THREAD

**Issue by michaelaye** [vpython/vpython-jupyter#95]
Currently, the vpython jupyterlab extension package asks for jupyterlab to be < 2.0.0.
Can we have a version for Jupyterlab >= 2.0.0?

**Comment by sntgluca** [comment]
Hi all,
just a _minor_ comment - I would argue it would be more appropriate to update your extension mechanism for JupyterLab 3.x...

Thanks for considering this! Looking forward to your progress...

**Comment by jcoady** [comment]
The vpython extension for JuptyerLab >= 2.0.0 are now available.

The vpython extension for JuptyerLab 3 and vpython version 7.6.1 can be installed with the command.

pip install jupyterlab-vpython==3.0.4

The vpython extension for JupyterLab 2 and vpython version 7.6.1 can be installed with the command.

jupyter labextension install vpython@2.0.1

**Comment by jcoady** [comment]
The vpython extension for JupyterLab is now available so closing this issue.
